name: Build and Publish Tauri App

on:
  push:
    tags:
      - 'none'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      
        with:
          node-version: 16
      - run: |
          npm install -g tauri
          tauri install
          tauri build
      - name: Create Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Tauri App
          path: tauri/build
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Tauri App
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tauri/build
          asset_name: Tauri App
          asset_content_type: application/zip
